fix: validate tuples for non-nil subj
ory/keto pull request #1013
Opened 2022-09-08 11:43 UTC by hperl

This PR adds a validation to reject request where both the subject id and the subject set are nil

2022-09-08 13:14 UTC, zepatrik requested changes
To ensure this regression does not happen again we should add a test :wink:

2022-09-09 12:10 UTC, zepatrik reviewed
Just some minor stuff and we're good to go :tada:

2022-09-09 12:10 UTC, zepatrik commented on ketoapi/public_api_definitions.go
> +		return ErrNilSubject
```suggestion
		return errors.WithStack(ErrNilSubject)
```

2022-09-09 12:10 UTC, zepatrik commented on internal/relationtuple/transact_server.go
> +			h.d.Writer().WriteError(w, r, errors.WithStack(herodot.ErrBadRequest.WithError(err.Error())))
```suggestion
			h.d.Writer().WriteError(w, r, err)
```

The error returned by validate should already be a `herodot.ErrBadRequest` with the right details and stack.

2022-09-09 12:10 UTC, zepatrik commented on internal/relationtuple/transact_server.go
> +		h.d.Writer().WriteError(w, r, errors.WithStack(herodot.ErrBadRequest.WithError(err.Error())))
same here
```suggestion
		h.d.Writer().WriteError(w, r, err)
```

2022-09-09 12:51 UTC, hperl commented on go.mod
> +	github.com/ory/keto/internal/httpclient-next => ./internal/httpclient-next
the client has a dependency on "golang.org/x/oauth2". Isn't the whole client autogenerated?

2022-09-09 12:56 UTC, zepatrik commented on go.mod
> +	github.com/ory/keto/internal/httpclient-next => ./internal/httpclient-next
Yes, but you could add a `rm internal/httpclient/go.*` to the `make sdk` target.

2022-09-09 12:57 UTC, zepatrik commented on go.mod
> +	github.com/ory/keto/internal/httpclient-next => ./internal/httpclient-next
And the dependency will then be tracked in this `go.mod`

2022-09-13 12:11 UTC, hperl commented on go.mod
> +	github.com/ory/keto/internal/httpclient-next => ./internal/httpclient-next
agreed, done!

2022-09-14 11:41 UTC, hperl commented
@aeneasr this is the PR that contains the removal of the database constraint. I also had to update the generated HTTP client to test for the regression, since the old client never allowed empty strings to be transmitted.

2022-09-14 12:36 UTC, aeneasr approved these changes

2022-09-14 12:40 UTC, merged