feat: switch to otelx
ory/keto pull request #861
Opened 2022-03-22 13:46 UTC by icyphox

## Related issue(s)

## Checklist

- [ ] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md).
- [ ] I have referenced an issue containing the design document if my change
      introduces a new feature.
- [ ] I am following the
      [contributing code guidelines](../blob/master/CONTRIBUTING.md#contributing-code).
- [ ] I have read the [security policy](../security/policy).
- [ ] I confirm that this pull request does not address a security
      vulnerability. If this pull request addresses a security. vulnerability, I
      confirm that I got green light (please contact
      [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push
      the changes.
- [ ] I have added tests that prove my fix is effective or that my feature
      works.
- [ ] I have added or changed [the documentation](docs/docs).

## Further Comments

2022-04-14 11:24 UTC, zepatrik reviewed
This looks good, I would merge it once https://github.com/ory/x/pull/479 is done :+1:

2022-04-14 16:25 UTC, aeneasr requested changes
Please update the tracing example (if required): https://github.com/ory/keto/blob/master/docker-compose-tracing.yml

and also add a guide to show how to do tracing either under the keto guides section: https://www.ory.sh/docs/keto

2022-04-21 08:36 UTC, icyphox commented
@aeneasr The tracing in Keto isn't complete yet; I think I'll add the docs for it once I start working on in-depth tracing in Keto.

2022-04-28 21:27 UTC, aeneasr commented
Ok :) Should we mark this PR as draft then?

2022-05-12 13:20 UTC, aeneasr commented
@icyphox is this the version you use in cloud?

2022-05-12 16:29 UTC, zepatrik commented on go.mod
> +	golang.org/x/crypto v0.0.0-20210921155107-089bfa567519 // indirect
I guess this needs to be reverted/adjusted.

2022-05-13 10:42 UTC, zepatrik approved these changes

2022-05-13 11:00 UTC, merged